# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: label_map.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='label_map.proto',
  package='fmcg_detection',
  serialized_pb=_b('\n\x0flabel_map.proto\x12\x0e\x66mcg_detection\" \n\x04Item\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\"/\n\x08LabelMap\x12#\n\x05items\x18\x01 \x03(\x0b\x32\x14.fmcg_detection.Item')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='fmcg_detection.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='fmcg_detection.Item.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='fmcg_detection.Item.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=67,
)


_LABELMAP = _descriptor.Descriptor(
  name='LabelMap',
  full_name='fmcg_detection.LabelMap',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='fmcg_detection.LabelMap.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=116,
)

_LABELMAP.fields_by_name['items'].message_type = _ITEM
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['LabelMap'] = _LABELMAP

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'label_map_pb2'
  # @@protoc_insertion_point(class_scope:fmcg_detection.Item)
  ))
_sym_db.RegisterMessage(Item)

LabelMap = _reflection.GeneratedProtocolMessageType('LabelMap', (_message.Message,), dict(
  DESCRIPTOR = _LABELMAP,
  __module__ = 'label_map_pb2'
  # @@protoc_insertion_point(class_scope:fmcg_detection.LabelMap)
  ))
_sym_db.RegisterMessage(LabelMap)


# @@protoc_insertion_point(module_scope)
